### ISSUE TITLE
Scanner count differs from Model_Grabber

### ISSUE THREAD

**Issue by jpummill** [Confuzu/CivitAI_scanner#1]
Hi Confuzu.  Wanted to let you know that the CivitAI_Scanner is providing a different count of resources than the CivitAI_Model_Grabber.

Scanner shows 119 items while model grabber shows 533 items for author Supremo (example below). 

For Author:  Supremo

CivitAI_scanner$ wc supremo_output.csv
  (( 119 Lines ))   246 28468 supremo_output.csv

CivitAI_Model_grabber$ python civitAI_Model_downloader.py Supremo --max_threads 5
Processing username: Supremo, Download type: All
Total items for username Supremo: 533

**Comment by Confuzu** [comment]
Thanks,
The script still had the old pagination system of the API. I have installed the new system and it is running again

**Comment by jpummill** [comment]
Thank you
